### ISSUE TITLE
GetQuestsCompleted error

### ISSUE THREAD

**Issue by dartraiden** [Ravendwyr/HandyNotes_HallowsEnd#8]
[9.0.1] GetQuestsCompleted was moved to C_QuestLog.GetAllCompletedQuestIDs() and returns quest IDs an a sorted array

```
{
	[1] = 56775,
	[2] = 58208,
	[3] = 58209,
}
```

**Comment by Ravendwyr** [comment]
Crap I forgot about this. >.<

I've amended the code and a new alpha package will be on CurseForge soon. Let me know how it goes. 🙂

**Comment by dartraiden** [comment]
It show all buckets if "Show completed" is disabled - OK
But it miss some buckets (Westfall, Stormwind, Goldshire, Northrend at all) if "Show completed" is enabled

![Wow_F8sD7BVmaW](https://user-images.githubusercontent.com/5046855/96364106-70ec1a80-1141-11eb-825b-90b0ca192e88.jpg)

![Wow_nG3eXwyfZr](https://user-images.githubusercontent.com/5046855/96364109-734e7480-1141-11eb-96f0-b5feb84382be.jpg)

**Comment by epigramx** [comment]
Fix because the author's upload takes a while:

at 228 of Core.lua:
```
		--completedQuests = GetQuestsCompleted(completedQuests)
		local tmpPairs = C_QuestLog.GetAllCompletedQuestIDs()
		for _, id in ipairs(tmpPairs) do 
			completedQuests[id] = "true";
		end
```

**Comment by dartraiden** [comment]
Yes, it works after this fix.
```
		local tmpPairs = C_QuestLog.GetAllCompletedQuestIDs()
		for _, id in ipairs(tmpPairs) do 
			completedQuests[id] = "true";
		end
```
